[project]
name = "agentic-ai-hackathon"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Shohei Fujieda", email = "96054771+ShoheiFujieda@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-adk>=2.11.0",
    "google-cloud-firestore>=2.34.0",
]

[project.scripts]
agentic-ai-hackathon = "agentic_ai_hackathon:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
